spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gaenolja?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: kr.co.fastcampus.eatgo
  config-location: classpath:/mapper/SqlMapConfig.xml